### ISSUE TITLE
[Question] Does tfcrypt uses full key feature when generating random bytes with "-R" option?

### ISSUE THREAD

**Issue by phantomcraft** [lynxlynx/tfcrypt#4]
I compiled my tfcrypt with full key option enabled in "tfcrypt_defs.h", I wanna know if the "-R" option uses full key (160 byte chunk) when seeded with a random source.

**Comment by strlcat** [comment]
according to strace, yes it does :)

**Comment by phantomcraft** [comment]
One more question:

Does it use the 128/160 byte chunk directly or hash it before generating the random stream?

**Comment by strlcat** [comment]
It uses the chunk directly. Relevant files to look into: tfc_random.c, tfprng.c, tfe.c. Basically, the key is used directly to cycle encrypt the IV over and over, emitting encrypted IV as result. IV is initialized to zero at beginning.
